export const SUBMIT_ORDER_REQUEST = "SUBMIT_ORDER_REQUEST";
export const SUBMIT_ORDER_RESPONSE = "SUBMIT_ORDER_RESPONSE";

export const GET_INFO_USER_RESPONSE = "GET_INFO_USER_RESPONSE";

export const GET_MENU_FOOD_RESPONSE = "GET_MENU_FOOD_RESPONSE";

export const CHOOSE_FOOD_RESPONSE = "CHOOSE_FOOD_RESPONSE";
